### ISSUE TITLE
Error code 522，the example api doesn't work "https://api.pushshift.io/reddit/search/comment/?q=science"

### ISSUE THREAD

**Issue by Yeqishen** [pushshift/api#113]
Hello, the example api doesn't work: "https://api.pushshift.io/reddit/search/comment/?q=science"
![image](https://user-images.githubusercontent.com/91174990/189825957-6ee66639-aeec-4deb-a2c1-91aca911a679.png)

**Comment by r92546024** [comment]
same issue. Me, too.
Suspect API server has issue.

**Comment by Yeqishen** [comment]
> same issue. Me, too. Suspect API server has issue.

It's okay now.
