### ISSUE TITLE
"fields" query param is broken for submissions

### ISSUE THREAD

**Issue by yaylinda** [pushshift/api#15]
[Bug]

This works fine (`/comment`):
https://api.pushshift.io/reddit/search/comment?subreddit=dataisbeautiful&fields=body

While returns "Internal Server Error" (`/submission`):
https://api.pushshift.io/reddit/search/submission?subreddit=dataisbeautiful&fields=body

**Comment by pushshift** [comment]
Fixed -- Sorry for the delay and thanks for the bug report.  

https://api.pushshift.io/reddit/search/submission/?fields=selftext
