### ISSUE TITLE
Search Submissions by Link

### ISSUE THREAD

**Issue by ronnyli** [pushshift/api#19]
Hi, I was wondering if it's possible to search link posts by the url they link to? For example, [this post](https://www.reddit.com/r/aww/comments/5m1kat/my_kitten_fell_asleep_in_a_container_today_and_it/) does not contain the URL `https://imgur.com/hyLlADL` anywhere in its title or selftext but I would like to be able to find it using that query.

Thank you!

**Comment by pushshift** [comment]
Let me check if this is being indexed and get back to you shortly.

**Comment by pushshift** [comment]
Hey there!  It is being indexed!  The API just didn't know how to handle the logic.  I've added support for it.  

Example:

http://api.pushshift.io/reddit/submission/search/?url=http://imgur.com/hyLlADL

**Comment by ronnyli** [comment]
Wow, amazing! Thank you!
