### ISSUE TITLE
num_comments causes server error

### ISSUE THREAD

**Issue by tamirvs** [pushshift/api#2]
when using `sort_type=num_comments` in the `search/comment` endpoint the server returns **Internal Server Error**  
It works fine for the `search/submission` endpoint though

**Comment by pushshift** [comment]
Hey there!  You're right that the server shouldn't return an "Internal Server Error" -- That's an error that should be catched.  However, comment objects don't have a "num_comments" field so you can't sort by that for comments.  What are you trying to do exactly?

**Comment by tamirvs** [comment]
According to the README, the accepted values for `sort_type` are:
> "score", "num_comments", "created_utc"

So I guess it should be fixed.  
I wasn't trying anything specific, just playing with the api..

**Comment by pushshift** [comment]
Good catch.  I'll correct that.
