### ISSUE TITLE
API tags not working properly

### ISSUE THREAD

**Issue by JonathanVusich** [pushshift/api#21]
[https://api.pushshift.io/reddit/submission/search/?subreddit=askreddit&size=500&sort=asc&after1315271853](url)

This API request should display any posts made after the epoch 1315271853 (unless I am way off base with the API documentation), but instead displays the first 500 posts on the subreddit, which are all before that epoch. 

Thoughts?

**Comment by pushshift** [comment]
The URL you used as an example seems to have a type.  There is no equal sign between the after parameter and the epoch time.  

Try this:

https://api.pushshift.io/reddit/submission/search/?subreddit=askreddit&size=500&sort=asc&after=1315271853

**Comment by JonathanVusich** [comment]
That works for me. Sorry for wasting your time! :)

**Comment by pushshift** [comment]
Never a waste! Glad you are finding use of the API! 

Good luck!
