### ISSUE TITLE
/reddit/search/submission not respecting ids parameter

### ISSUE THREAD

**Issue by timbennett** [pushshift/api#3]
**What I'm trying to do:** get submission details (specifically created_utc) for [this submission](https://www.reddit.com/r/australia/comments/4luo9o/a_melbourne_cafe_has_seemingly_outwankered_the/).

**How I'm trying to do it:** https://api.pushshift.io/reddit/search/submission/?ids=4luo9o

**What's happening instead:** API returns ten unrelated results instead (see [output.txt](https://github.com/pushshift/api/files/1297847/output.txt)).

**Comment by pushshift** [comment]
Thanks for this report.  I can verify that this is a bug.  I'll inspect the code soon and follow-up with a fix (hopefully relatively shortly).  

Thank you Tim!

**Comment by timbennett** [comment]
appears to be fixed

**Comment by pushshift** [comment]
Yes -- sorry I didn't update this ticket. I've been focused on getting the new API ready for prime time.

Glad this got fixed, though!
