### ISSUE TITLE
metadata isn't returned

### ISSUE THREAD

**Issue by emlazzarin** [pushshift/api#35]
In this documentation, `metadata` is described, but I haven't seen it returned on any queries. It's very useful to have. Is this an intended omission or a bug?

**Comment by pushshift** [comment]
Which endpoint isn't returning metadata when you pass &metadata=true ?

**Comment by emlazzarin** [comment]
Oh, the documentation doesn't mention that it's a query parameter - only that it is returned. I added this to the documentation in PR #36. Sorry about that - thanks!
