### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by psimm** [pushshift/api#47]
Hi, the service seems to be unavailable. Currently, all calls result in a 502 Bad Gateway error, for example <https://api.pushshift.io/reddit/submission/comment_ids/6uey5x>

Update: I checked again at 2020-04-02 17:35:46 CEST and it works again. I'll take the opportunity to say thank you for providing the API, it's very useful :)

**Comment by pushshift** [comment]
Fixed -- thanks for the report!
