### ISSUE TITLE
API not working 

### ISSUE THREAD

**Issue by Ykisi** [pushshift/api#86]
Trying to get data from reddit but the API seems to be stuck in a loop/ not working.
(I tried several times on different dates and after 3-4 hours I stopped the code execution)

any reason why?

**code:**
  start_epoch=int(date)
  user=user

  gen = api.search_submissions(after='365d',
                               before=start_epoch,
                               autor=user,
                               filter=['title', 'selftext', 'subreddit','author'])

  results = list(gen)

**warnings:**
/usr/local/lib/python3.7/dist-packages/psaw/PushshiftAPI.py:192: UserWarning: Got non 200 code 525
  warnings.warn("Got non 200 code %s" % response.status_code)
/usr/local/lib/python3.7/dist-packages/psaw/PushshiftAPI.py:180: UserWarning: Unable to connect to pushshift.io. Retrying after backoff.
  warnings.warn("Unable to connect to pushshift.io. Retrying after backoff.")

**Comment by Rajesh-hugar** [comment]
I am also facing the same issue
